use_frameworks!
platform :ios, '12.0'

target 'WeChatPaySDK_Example' do
  pod 'WeChatPaySDK', :path => '../'
  pod 'WechatOpenSDK'
  target 'WeChatPaySDK_Tests' do
    inherit! :search_paths

    
  end
end
